namespace: nn708
name: openwrt
version: 0.1.0
readme: README.md
authors:
  - NN708
description: Ansible collection to configure your OpenWrt devices more quickly and automatically (without Python)
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags:
  - openwrt
  - lede
  - uci
  - networking
dependencies: {}
repository: https://github.com/NN708/ansible-openwrt
issues: https://github.com/NN708/ansible-openwrt/issues