---
- name: Configure system
  uci:
    command: set
    key: system.@system[0]
    value:
      hostname: "{{ openwrt_system_hostname | default(omit) }}"
      timezone: "{{ tzdata[openwrt_system_zonename] | default(omit) }}"
      zonename: "{{ openwrt_system_zonename | default(omit) }}"

- name: Commit changes
  uci:
    command: commit
  notify: reload system

- name: Configure NTP service
  uci:
    command: set
    key: system.ntp
    value:
      enable_server: "{{ openwrt_ntp_enable_server | default(omit) }}"

- name: Commit changes
  uci:
    command: commit
  notify: restart sysntpd
