---
- name: Install ddns-scripts
  opkg:
    name: ddns-scripts
    state: present

- name: Install ddns-scripts_no-ip_com
  when: >
    (openwrt_ddns_ipv4_service_name is defined and openwrt_ddns_ipv4_service_name == "no-ip.com")
    or (openwrt_ddns_ipv6_service_name is defined and openwrt_ddns_ipv6_service_name == "no-ip.com")
  opkg:
    name: ddns-scripts_no-ip_com
    state: present

- name: Start and enable ddns service
  service:
    name: ddns
    state: started
    enabled: yes

- include_tasks: service.yml
  vars:
    _openwrt_ddns:
      service: myddns_ipv4
      enabled: "{{ openwrt_ddns_ipv4_enabled }}"
      lookup_host: "{{ openwrt_ddns_ipv4_lookup_host | default(omit) }}"
      domain: "{{ openwrt_ddns_ipv4_domain | default(omit) }}"
      username: "{{ openwrt_ddns_ipv4_username | default(omit) }}"
      password: "{{ openwrt_ddns_ipv4_password | default(omit) }}"
      interface: "{{ openwrt_ddns_ipv4_interface | default(omit) }}"
      service_name: "{{ openwrt_ddns_ipv4_service_name | default(omit) }}"
      update_url: "{{ openwrt_ddns_ipv4_update_url | default(omit) }}"
      update_script: "{{ openwrt_ddns_ipv4_update_script | default(omit) }}"
      ip_source: "{{ openwrt_ddns_ipv4_ip_source | default(omit) }}"
      ip_network: "{{ openwrt_ddns_ipv4_ip_network | default(omit) }}"
      ip_url: "{{ openwrt_ddns_ipv4_ip_url | default(omit) }}"
      ip_interface: "{{ openwrt_ddns_ipv4_ip_interface | default(omit) }}"
      ip_script: "{{ openwrt_ddns_ipv4_ip_script | default(omit) }}"

- include_tasks: service.yml
  vars:
    _openwrt_ddns:
      service: myddns_ipv6
      enabled: "{{ openwrt_ddns_ipv6_enabled }}"
      lookup_host: "{{ openwrt_ddns_ipv6_lookup_host | default(omit) }}"
      domain: "{{ openwrt_ddns_ipv6_domain | default(omit) }}"
      username: "{{ openwrt_ddns_ipv6_username | default(omit) }}"
      password: "{{ openwrt_ddns_ipv6_password | default(omit) }}"
      interface: "{{ openwrt_ddns_ipv6_interface | default(omit) }}"
      service_name: "{{ openwrt_ddns_ipv6_service_name | default(omit) }}"
      update_url: "{{ openwrt_ddns_ipv6_update_url | default(omit) }}"
      update_script: "{{ openwrt_ddns_ipv6_update_script | default(omit) }}"
      ip_source: "{{ openwrt_ddns_ipv6_ip_source | default(omit) }}"
      ip_network: "{{ openwrt_ddns_ipv6_ip_network | default(omit) }}"
      ip_url: "{{ openwrt_ddns_ipv6_ip_url | default(omit) }}"
      ip_interface: "{{ openwrt_ddns_ipv6_ip_interface | default(omit) }}"
      ip_script: "{{ openwrt_ddns_ipv6_ip_script | default(omit) }}"

- name: Commit changes
  uci:
    command: commit
  notify: restart ddns
