---
- name: Install ddns-scripts
  opkg:
    name: ddns-scripts
    state: present

- name: Install ddns-scripts_no-ip_com
  when: >
    (openwrt_ddns_ipv4_service_name is defined and openwrt_ddns_ipv4_service_name == "no-ip.com")
    or (openwrt_ddns_ipv6_service_name is defined and openwrt_ddns_ipv6_service_name == "no-ip.com")
  opkg:
    name: ddns-scripts-noip
    state: present

- name: Start and enable ddns service
  service:
    name: ddns
    state: started
    enabled: yes

- include_tasks: service.yml
  vars:
    _openwrt_ddns:
      service: myddns_ipv4
      enabled: "{{ openwrt_ddns_ipv4_enabled }}"
      lookup_host: "{{ openwrt_ddns_ipv4_lookup_host }}"
      domain: "{{ openwrt_ddns_ipv4_domain }}"
      username: "{{ openwrt_ddns_ipv4_username }}"
      password: "{{ openwrt_ddns_ipv4_password }}"
      interface: "{{ openwrt_ddns_ipv4_interface }}"
      service_name: "{{ openwrt_ddns_ipv4_service_name }}"
      update_url: "{{ openwrt_ddns_ipv4_update_url }}"
      update_script: "{{ openwrt_ddns_ipv4_update_script }}"
      ip_source: "{{ openwrt_ddns_ipv4_ip_source }}"
      ip_network: "{{ openwrt_ddns_ipv4_ip_network }}"
      ip_url: "{{ openwrt_ddns_ipv4_ip_url }}"
      ip_interface: "{{ openwrt_ddns_ipv4_ip_interface }}"
      ip_script: "{{ openwrt_ddns_ipv4_ip_script }}"

- include_tasks: service.yml
  vars:
    _openwrt_ddns:
      service: myddns_ipv6
      enabled: "{{ openwrt_ddns_ipv6_enabled }}"
      lookup_host: "{{ openwrt_ddns_ipv6_lookup_host }}"
      domain: "{{ openwrt_ddns_ipv6_domain }}"
      username: "{{ openwrt_ddns_ipv6_username }}"
      password: "{{ openwrt_ddns_ipv6_password }}"
      interface: "{{ openwrt_ddns_ipv6_interface }}"
      service_name: "{{ openwrt_ddns_ipv6_service_name }}"
      update_url: "{{ openwrt_ddns_ipv6_update_url }}"
      update_script: "{{ openwrt_ddns_ipv6_update_script }}"
      ip_source: "{{ openwrt_ddns_ipv6_ip_source }}"
      ip_network: "{{ openwrt_ddns_ipv6_ip_network }}"
      ip_url: "{{ openwrt_ddns_ipv6_ip_url }}"
      ip_interface: "{{ openwrt_ddns_ipv6_ip_interface }}"
      ip_script: "{{ openwrt_ddns_ipv6_ip_script }}"

- name: Commit changes
  uci:
    command: commit
  notify: restart ddns
